### ISSUE TITLE
Create CherryTwist public discussions location

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/alkemio#54]

**Comment by positivedefinite** [comment]
Consider going for FOSS:

https://medium.com/@sammyjohnsonweb/use-riot-not-discord-for-foss-and-privacy-respecting-communities-d25f9ae2cb5

Audio/video: https://jitsi.org/

Text: https://about.riot.im/

**Comment by wordsmyth73** [comment]
Hi positivedefinite,

Thanks for the comments - makes sense, was more just habit / rushing that we put down discord in the title. 

Goal is to have a discussion / collaboration platform for topics around CT - and am very keen to get more familiar with riot / matrix in general. Jitsi am well familar with + works well. 

@ReneHonig - thoughts?

**Comment by ReneHonig** [comment]
I completely agree with the suggestion to leverage  open source solutions for public discussions. We have used Jitsi frequently on other projects and the use of Riot / Matrix makes sense to. We could also look into https://mastodon.social/about. All of these solutions have the option to be self-hosted. Just need to be careful not to have too many overlapping features in different tools as that would negatively impact the user experience.

@GhostOnTheFiber , any thoughts?

**Comment by techsmyth** [comment]
Actually I think some of the discussions we are having should be public - so want to keep this issue open so it is on our radar.

**Comment by techsmyth** [comment]
Landed on using Github discussions which are working great.
