### ISSUE TITLE
Communication platforms 

### ISSUE THREAD

**Issue by GhostOnTheFiber** [alkem-io/alkemio#90]
As of this moment most of the communication between contributors occurs on discord. 
We would like to have a convenient set of places where people go to talk and work on CherryTwist together.

We currently have:
Location | Use
------------ | -----
gdrive | contributors: ephemeral storage for collaboration, these will be moved to github issues
GitHub issues | public: Longer term tracking of work/issues/ideas
discord(or Matrix) |  contributors: "real time" discussions about cherrytwists work/github issues/ideas

Once more people join the project we would like to expand to:
Location | Use
------------ | -----
gdrive(or NextCloud) | contributors: ephemeral storage for collaboration, these will be moved to github issues
GitHub issues | public: Longer term tracking of work/issues/ideas
discord(or Matrix) |  contributors: "real time" discussions about cherrytwists work/github issues/ideas
discord(or Matrix) | Public: A way for individuals to ask questions, get support, and engage with cherrytwist and the contributors

This links with issue: #54

**Comment by techsmyth** [comment]
Keep alive
